name: Build .NET Project

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 

      - name: Instala o .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      - name: Restaurar dependências
        run: dotnet restore **/*.csproj

      - name: Compila o projeto
        run: dotnet build **/*.csproj --configuration Release

      - name: Executa testes
        run: dotnet test **/*.csproj --configuration Release